sudo: false
language: node_js
install: true
script: true
deploy:
  provider: s3
  access_key_id: AKIAJJN6T6DFEH6COLCA
  secret_access_key:
    secure: vG+psKyzssoSVU3XU+lE2n5Dfyx3ygA3bWLZQXPIQVnIIHzJjFjOV7rvWBJUatXO6ohggy18udFhbvArtCxvcDTCdOBeEgIdcm9JNKPv+pk4/tCrxn1Pix4axcKSlsOEqyNYqjEynybGkVWKlR1gXe1Kcu4+cEw3L6+Rzz1aEZ0=
  bucket: joul.aeirola.iki.fi
  region: eu-central-1
  acl: public_read
  on:
    repo: aeirola/christmas-cards
